[workspace]
members = [
    "crates/twin-cli",
    "crates/twin-app",
    "crates/twin-core",
    "crates/twin-store",
    "crates/twin-observation",
    "crates/twin-collectors",
    "crates/twin-emulate",
    "crates/twin-ebpf",
    "crates/twin-test",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
twin-core = { path = "crates/twin-core" }
twin-store = { path = "crates/twin-store" }
twin-app = { path = "crates/twin-app" }
twin-observation = { path = "crates/twin-observation" }
twin-collectors = { path = "crates/twin-collectors" }
twin-emulate = { path = "crates/twin-emulate" }
twin-ebpf = { path = "crates/twin-ebpf" }
twin-test = { path = "crates/twin-test" }
serde_yaml = "0.9"
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
thiserror = "1"
dirs = "5"
uuid = { version = "1", features = ["v4", "serde"] }
tempfile = "3"
zbus = { version = "5", default-features = true }
