[package]
name = "twin-collectors"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
twin-core = { workspace = true }
twin-observation = { workspace = true }
zbus = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
