[package]
name = "twin-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
twin-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
twin-core = { workspace = true }
